name: Deployment-prod

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: deploy-prod
        run: |
          echo "hellow"
          echo 'HOSTNAME=${{ secrets.HOSTNAME }}' >> hello.txt
          cat hello.txt

