name: Deployment-prod

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: deploy-prod
        env:
          MYHOSTNAME: ${{ secrets.HOSTNAME }}
        run: |
          echo "hellow"
          echo 'HOSTNAME=${{ secrets.HOSTNAME }}' >> hello.txt
          echo ${MYHOSTNAME}

